# Generated by Django 3.2.6 on 2022-04-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='athletes',
            field=models.ManyToManyField(related_name='athetles', to='general.Athlete'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coach',
            field=models.ManyToManyField(related_name='coaches', to='general.Coach'),
        ),
    ]
