# Generated by Django 3.2.6 on 2022-04-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20220416_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
